CREATE TABLE ciudad (
    id_ciudad NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,
    region VARCHAR2(100) NOT NULL,
    pais VARCHAR2(50) DEFAULT 'Chile' NOT NULL,
    observaciones VARCHAR2(200) DEFAULT 'Sin observaciones' NOT NULL,
    CONSTRAINT pk_ciudad PRIMARY KEY (id_ciudad),
    CONSTRAINT uq_ciudad_nombre UNIQUE (nombre, region)
);

CREATE TABLE sede (
    id_sede NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,
    direccion VARCHAR2(150) NOT NULL,
    capacidad_maxima NUMBER DEFAULT 100 NOT NULL,
    tipo_sede VARCHAR2(50) DEFAULT 'Cine convencional' NOT NULL,
    id_ciudad NUMBER NOT NULL,
    estado VARCHAR2(20) DEFAULT 'Activa' NOT NULL,
    CONSTRAINT pk_sede PRIMARY KEY (id_sede),
    CONSTRAINT fk_sede_ciudad FOREIGN KEY (id_ciudad) REFERENCES ciudad(id_ciudad),
    CONSTRAINT uq_sede_nombre UNIQUE (nombre, id_ciudad),
    CONSTRAINT ck_capacidad_positiva CHECK (capacidad_maxima > 0),
    CONSTRAINT ck_estado_sede CHECK (estado IN ('Activa', 'Inactiva', 'Mantenimiento'))
);

CREATE TABLE pelicula (
    id_pelicula NUMBER GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR2(100) NOT NULL,
    pais_origen VARCHAR2(50) NOT NULL,
    director VARCHAR2(100) NOT NULL,
    duracion_minutos NUMBER NOT NULL,
    genero VARCHAR2(50) DEFAULT 'Drama' NOT NULL,
    clasificacion VARCHAR2(10) DEFAULT 'TE' NOT NULL,
    sinopsis VARCHAR2(500) DEFAULT 'Sin sinopsis disponible' NOT NULL,
    CONSTRAINT pk_pelicula PRIMARY KEY (id_pelicula),
    CONSTRAINT uq_pelicula_titulo UNIQUE (titulo, director),
    CONSTRAINT ck_duracion_positiva CHECK (duracion_minutos > 0),
    CONSTRAINT ck_clasificacion_valida CHECK (clasificacion IN ('TE', '+7', '+14', '+18'))
);

CREATE TABLE funcion (
    id_funcion NUMBER GENERATED BY DEFAULT AS IDENTITY,
    fecha DATE NOT NULL,
    hora VARCHAR2(10) NOT NULL,
    precio_entrada NUMBER DEFAULT 5000 NOT NULL,
    estado_funcion VARCHAR2(20) DEFAULT 'Programada' NOT NULL,
    observaciones VARCHAR2(200) DEFAULT 'Sin observaciones' NOT NULL,
    id_sede NUMBER NOT NULL,
    CONSTRAINT pk_funcion PRIMARY KEY (id_funcion),
    CONSTRAINT fk_funcion_sede FOREIGN KEY (id_sede) REFERENCES sede(id_sede),
    CONSTRAINT ck_precio_positivo CHECK (precio_entrada > 0),
    CONSTRAINT ck_estado_funcion CHECK (estado_funcion IN ('Programada', 'En curso', 'Finalizada', 'Cancelada'))
);

CREATE TABLE proyeccion (
    id_funcion NUMBER NOT NULL,
    id_pelicula NUMBER NOT NULL,
    orden_proyeccion NUMBER DEFAULT 1 NOT NULL,
    comentarios VARCHAR2(200) DEFAULT 'Sin comentarios' NOT NULL,
    CONSTRAINT pk_proyeccion PRIMARY KEY (id_funcion, id_pelicula),
    CONSTRAINT fk_proyeccion_funcion FOREIGN KEY (id_funcion) REFERENCES funcion(id_funcion),
    CONSTRAINT fk_proyeccion_pelicula FOREIGN KEY (id_pelicula) REFERENCES pelicula(id_pelicula),
    CONSTRAINT ck_orden_positivo CHECK (orden_proyeccion > 0)
);

CREATE TABLE asistente (
    id_asistente NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,
    correo VARCHAR2(100) NOT NULL,
    telefono VARCHAR2(20) NOT NULL,
    edad NUMBER NOT NULL,
    ciudad_residencia VARCHAR2(100) DEFAULT 'No especificada' NOT NULL,
    tipo_asistente VARCHAR2(20) DEFAULT 'General' NOT NULL,
    CONSTRAINT pk_asistente PRIMARY KEY (id_asistente),
    CONSTRAINT uq_asistente_correo UNIQUE (correo),
    CONSTRAINT uq_asistente_telefono UNIQUE (telefono),
    CONSTRAINT ck_edad_valida CHECK (edad >= 0 AND edad <= 120),
    CONSTRAINT ck_tipo_asistente CHECK (tipo_asistente IN ('General', 'Estudiante', 'Profesional', 'Prensa'))
);

CREATE TABLE asistencia (
    id_funcion NUMBER NOT NULL,
    id_asistente NUMBER NOT NULL,
    entradas NUMBER DEFAULT 1 NOT NULL,
    fecha_compra DATE DEFAULT SYSDATE NOT NULL,
    metodo_pago VARCHAR2(20) DEFAULT 'Efectivo' NOT NULL,
    comentarios VARCHAR2(200) DEFAULT 'Sin comentarios' NOT NULL,
    CONSTRAINT pk_asistencia PRIMARY KEY (id_funcion, id_asistente),
    CONSTRAINT fk_asistencia_funcion FOREIGN KEY (id_funcion) REFERENCES funcion(id_funcion),
    CONSTRAINT fk_asistencia_asistente FOREIGN KEY (id_asistente) REFERENCES asistente(id_asistente),
    CONSTRAINT ck_entradas_positivas CHECK (entradas > 0),
    CONSTRAINT ck_metodo_pago CHECK (metodo_pago IN ('Efectivo', 'Tarjeta', 'Transferencia'))
);

CREATE TABLE jurado (
    id_jurado NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,
    correo VARCHAR2(100) NOT NULL,
    especialidad VARCHAR2(100) NOT NULL,
    pais_origen VARCHAR2(50) DEFAULT 'Chile' NOT NULL,
    experiencia_anos NUMBER DEFAULT 0 NOT NULL,
    tipo_jurado VARCHAR2(20) DEFAULT 'Invitado' NOT NULL,
    biografia VARCHAR2(500) DEFAULT 'Sin biografia disponible' NOT NULL,
    CONSTRAINT pk_jurado PRIMARY KEY (id_jurado),
    CONSTRAINT uq_jurado_correo UNIQUE (correo),
    CONSTRAINT ck_experiencia_valida CHECK (experiencia_anos >= 0),
    CONSTRAINT ck_tipo_jurado CHECK (tipo_jurado IN ('Invitado', 'Permanente', 'Honorario'))
);

CREATE TABLE participacion_jurado (
    id_jurado NUMBER NOT NULL,
    id_funcion NUMBER NOT NULL,
    rol_participacion VARCHAR2(50) DEFAULT 'Evaluador' NOT NULL,
    comentarios VARCHAR2(200) DEFAULT 'Sin comentarios' NOT NULL,
    CONSTRAINT pk_participacion_jurado PRIMARY KEY (id_jurado, id_funcion),
    CONSTRAINT fk_part_jurado FOREIGN KEY (id_jurado) REFERENCES jurado(id_jurado),
    CONSTRAINT fk_part_funcion FOREIGN KEY (id_funcion) REFERENCES funcion(id_funcion),
    CONSTRAINT ck_rol_participacion CHECK (rol_participacion IN ('Evaluador', 'Moderador', 'Invitado especial'))
);

CREATE TABLE evaluacion (
    id_jurado NUMBER NOT NULL,
    id_pelicula NUMBER NOT NULL,
    puntuacion NUMBER NOT NULL,
    comentario VARCHAR2(500) DEFAULT 'Sin comentarios' NOT NULL,
    fecha_evaluacion DATE DEFAULT SYSDATE NOT NULL,
    categoria_evaluada VARCHAR2(50) DEFAULT 'General' NOT NULL,
    CONSTRAINT pk_evaluacion PRIMARY KEY (id_jurado, id_pelicula),
    CONSTRAINT fk_eval_jurado FOREIGN KEY (id_jurado) REFERENCES jurado(id_jurado),
    CONSTRAINT fk_eval_pelicula FOREIGN KEY (id_pelicula) REFERENCES pelicula(id_pelicula),
    CONSTRAINT ck_puntuacion_valida CHECK (puntuacion >= 1 AND puntuacion <= 10),
    CONSTRAINT ck_categoria_eval CHECK (categoria_evaluada IN ('General', 'Direccion', 'Actuacion', 'Guion', 'Fotografia', 'Sonido'))
);

CREATE TABLE premiacion (
    id_premio NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_pelicula NUMBER NOT NULL,
    categoria VARCHAR2(100) NOT NULL,
    edicion NUMBER NOT NULL,
    posicion NUMBER DEFAULT 1 NOT NULL,
    descripcion VARCHAR2(300) DEFAULT 'Sin descripcion' NOT NULL,
    fecha_premiacion DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_premiacion PRIMARY KEY (id_premio),
    CONSTRAINT fk_premio_pelicula FOREIGN KEY (id_pelicula) REFERENCES pelicula(id_pelicula),
    CONSTRAINT uq_premio_categoria_edicion UNIQUE (categoria, edicion, posicion),
    CONSTRAINT ck_edicion_valida CHECK (edicion > 0),
    CONSTRAINT ck_posicion_valida CHECK (posicion >= 1 AND posicion <= 3)
);

-- 1. Ciudad
INSERT INTO ciudad (nombre, region, pais) VALUES ('Santiago', 'Metropolitana', 'Chile');
INSERT INTO ciudad (nombre, region, pais) VALUES ('Valparaíso', 'Valparaíso', 'Chile');
INSERT INTO ciudad (nombre, region, pais) VALUES ('Concepción', 'Biobío', 'Chile');
INSERT INTO ciudad (nombre, region, pais) VALUES ('Buenos Aires', 'CABA', 'Argentina');
INSERT INTO ciudad (nombre, region, pais) VALUES ('Lima', 'Lima Metropolitana', 'Perú');

-- 2. Sede
INSERT INTO sede (nombre, direccion, capacidad_maxima, tipo_sede, id_ciudad) VALUES ('Cine Arte Alameda', 'Av. Libertador 123', 300, 'Cine convencional', 1);
INSERT INTO sede (nombre, direccion, capacidad_maxima, tipo_sede, id_ciudad) VALUES ('Teatro Municipal Valpo', 'Calle Bellavista 456', 500, 'Teatro', 2);
INSERT INTO sede (nombre, direccion, capacidad_maxima, tipo_sede, id_ciudad) VALUES ('Cine Biobío', 'Av. Los Carrera 789', 250, 'Cine independiente', 3);
INSERT INTO sede (nombre, direccion, capacidad_maxima, tipo_sede, id_ciudad) VALUES ('Cine Gaumont', 'Av. Rivadavia 321', 400, 'Cine histórico', 4);
INSERT INTO sede (nombre, direccion, capacidad_maxima, tipo_sede, id_ciudad) VALUES ('Cine UVK', 'Av. Benavides 654', 350, 'Cine comercial', 5);

-- 3. Pelicula
INSERT INTO pelicula (titulo, pais_origen, director, duracion_minutos, genero, clasificacion) VALUES ('El Viaje', 'Chile', 'Juan Pérez', 120, 'Drama', '+14');
INSERT INTO pelicula (titulo, pais_origen, director, duracion_minutos, genero, clasificacion) VALUES ('Sueños del Mar', 'Argentina', 'María López', 90, 'Romance', 'TE');
INSERT INTO pelicula (titulo, pais_origen, director, duracion_minutos, genero, clasificacion) VALUES ('Luz en la Oscuridad', 'Perú', 'Carlos Ramírez', 110, 'Suspenso', '+18');
INSERT INTO pelicula (titulo, pais_origen, director, duracion_minutos, genero, clasificacion) VALUES ('Camino al Futuro', 'Chile', 'Ana Torres', 100, 'Ciencia Ficción', '+7');
INSERT INTO pelicula (titulo, pais_origen, director, duracion_minutos, genero, clasificacion) VALUES ('Risas Eternas', 'México', 'Pedro Sánchez', 95, 'Comedia', 'TE');

-- 4. Funcion
INSERT INTO funcion (fecha, hora, precio_entrada, estado_funcion, id_sede) VALUES (SYSDATE, '18:00', 5000, 'Programada', 1);
INSERT INTO funcion (fecha, hora, precio_entrada, estado_funcion, id_sede) VALUES (SYSDATE + 1, '20:00', 6000, 'Programada', 2);
INSERT INTO funcion (fecha, hora, precio_entrada, estado_funcion, id_sede) VALUES (SYSDATE + 2, '19:30', 4500, 'Programada', 3);
INSERT INTO funcion (fecha, hora, precio_entrada, estado_funcion, id_sede) VALUES (SYSDATE + 3, '21:00', 7000, 'Programada', 4);
INSERT INTO funcion (fecha, hora, precio_entrada, estado_funcion, id_sede) VALUES (SYSDATE + 4, '17:00', 5500, 'Programada', 5);

-- 5. Proyeccion
INSERT INTO proyeccion (id_funcion, id_pelicula, orden_proyeccion) VALUES (1, 1, 1);
INSERT INTO proyeccion (id_funcion, id_pelicula, orden_proyeccion) VALUES (2, 2, 1);
INSERT INTO proyeccion (id_funcion, id_pelicula, orden_proyeccion) VALUES (3, 3, 1);
INSERT INTO proyeccion (id_funcion, id_pelicula, orden_proyeccion) VALUES (4, 4, 1);
INSERT INTO proyeccion (id_funcion, id_pelicula, orden_proyeccion) VALUES (5, 5, 1);

-- 6. Asistente
INSERT INTO asistente (nombre, correo, telefono, edad, ciudad_residencia, tipo_asistente) VALUES ('Pedro Gómez', 'pedro.gomez@mail.com', '9991111', 28, 'Santiago', 'General');
INSERT INTO asistente (nombre, correo, telefono, edad, ciudad_residencia, tipo_asistente) VALUES ('Laura Martínez', 'laura.martinez@mail.com', '9992222', 22, 'Valparaíso', 'Estudiante');
INSERT INTO asistente (nombre, correo, telefono, edad, ciudad_residencia, tipo_asistente) VALUES ('Carlos Ramírez', 'carlos.ramirez@mail.com', '9993333', 35, 'Concepción', 'Profesional');
INSERT INTO asistente (nombre, correo, telefono, edad, ciudad_residencia, tipo_asistente) VALUES ('Ana Torres', 'ana.torres@mail.com', '9994444', 30, 'Buenos Aires', 'Prensa');
INSERT INTO asistente (nombre, correo, telefono, edad, ciudad_residencia, tipo_asistente) VALUES ('Sofía Díaz', 'sofia.diaz@mail.com', '9995555', 26, 'Lima', 'General');

-- 7. Asistencia
INSERT INTO asistencia (id_funcion, id_asistente, entradas, metodo_pago) VALUES (1, 1, 2, 'Tarjeta');
INSERT INTO asistencia (id_funcion, id_asistente, entradas, metodo_pago) VALUES (2, 2, 1, 'Efectivo');
INSERT INTO asistencia (id_funcion, id_asistente, entradas, metodo_pago) VALUES (3, 3, 3, 'Transferencia');
INSERT INTO asistencia (id_funcion, id_asistente, entradas, metodo_pago) VALUES (4, 4, 1, 'Tarjeta');
INSERT INTO asistencia (id_funcion, id_asistente, entradas, metodo_pago) VALUES (5, 5, 2, 'Efectivo');
INSERT INTO asistencia (id_funcion, id_asistente, entradas, metodo_pago) VALUES (1, 2, 150, 'Tarjeta');
INSERT INTO asistencia (id_funcion, id_asistente, entradas, metodo_pago) VALUES (1, 3, 130, 'Efectivo');
INSERT INTO asistencia (id_funcion, id_asistente, entradas, metodo_pago) VALUES (2, 1, 200, 'Tarjeta');
INSERT INTO asistencia (id_funcion, id_asistente, entradas, metodo_pago) VALUES (2, 4, 100, 'Efectivo');
INSERT INTO asistencia (id_funcion, id_asistente, entradas, metodo_pago) VALUES (3, 5, 60, 'Transferencia');
INSERT INTO asistencia (id_funcion, id_asistente, entradas, metodo_pago) VALUES (4, 1, 180, 'Efectivo');
INSERT INTO asistencia (id_funcion, id_asistente, entradas, metodo_pago) VALUES (4, 3, 100, 'Tarjeta');
INSERT INTO asistencia (id_funcion, id_asistente, entradas, metodo_pago) VALUES (5, 2, 180, 'Transferencia');
INSERT INTO asistencia (id_funcion, id_asistente, entradas, metodo_pago) VALUES (5, 4, 140, 'Tarjeta');

-- 8. Jurado
INSERT INTO jurado (nombre, correo, especialidad, pais_origen, experiencia_anos, tipo_jurado) VALUES ('Dr. Juan Herrera', 'juan.herrera@mail.com', 'Dirección', 'Chile', 10, 'Permanente');
INSERT INTO jurado (nombre, correo, especialidad, pais_origen, experiencia_anos, tipo_jurado) VALUES ('María Vega', 'maria.vega@mail.com', 'Actuación', 'Argentina', 8, 'Invitado');
INSERT INTO jurado (nombre, correo, especialidad, pais_origen, experiencia_anos, tipo_jurado) VALUES ('Ricardo Soto', 'ricardo.soto@mail.com', 'Guion', 'Perú', 12, 'Honorario');
INSERT INTO jurado (nombre, correo, especialidad, pais_origen, experiencia_anos, tipo_jurado) VALUES ('Diana Fuentes', 'diana.fuentes@mail.com', 'Fotografía', 'Chile', 15, 'Permanente');
INSERT INTO jurado (nombre, correo, especialidad, pais_origen, experiencia_anos, tipo_jurado) VALUES ('Fernando Ríos', 'fernando.rios@mail.com', 'Sonido', 'México', 20, 'Invitado');

-- 9. Participacion_Jurado
INSERT INTO participacion_jurado (id_jurado, id_funcion, rol_participacion) VALUES (1, 1, 'Evaluador');
INSERT INTO participacion_jurado (id_jurado, id_funcion, rol_participacion) VALUES (2, 2, 'Moderador');
INSERT INTO participacion_jurado (id_jurado, id_funcion, rol_participacion) VALUES (3, 3, 'Evaluador');
INSERT INTO participacion_jurado (id_jurado, id_funcion, rol_participacion) VALUES (4, 4, 'Invitado especial');
INSERT INTO participacion_jurado (id_jurado, id_funcion, rol_participacion) VALUES (5, 5, 'Evaluador');

-- 10. Evaluacion
INSERT INTO evaluacion (id_jurado, id_pelicula, puntuacion, comentario, categoria_evaluada) VALUES (1, 1, 9, 'Gran dirección', 'Direccion');
INSERT INTO evaluacion (id_jurado, id_pelicula, puntuacion, comentario, categoria_evaluada) VALUES (2, 2, 8, 'Buena actuación', 'Actuacion');
INSERT INTO evaluacion (id_jurado, id_pelicula, puntuacion, comentario, categoria_evaluada) VALUES (3, 3, 7, 'Historia interesante', 'Guion');
INSERT INTO evaluacion (id_jurado, id_pelicula, puntuacion, comentario, categoria_evaluada) VALUES (4, 4, 10, 'Fotografía impecable', 'Fotografia');
INSERT INTO evaluacion (id_jurado, id_pelicula, puntuacion, comentario, categoria_evaluada) VALUES (5, 5, 9, 'Excelente sonido', 'Sonido');

-- 11. Premiacion
INSERT INTO premiacion (id_pelicula, categoria, edicion, posicion, descripcion) VALUES (1, 'Mejor Dirección', 2025, 1, 'Premio a la mejor dirección');
INSERT INTO premiacion (id_pelicula, categoria, edicion, posicion, descripcion) VALUES (2, 'Mejor Actuación', 2025, 1, 'Premio a la mejor actuación');
INSERT INTO premiacion (id_pelicula, categoria, edicion, posicion, descripcion) VALUES (3, 'Mejor Guion', 2025, 1, 'Premio al mejor guion');
INSERT INTO premiacion (id_pelicula, categoria, edicion, posicion, descripcion) VALUES (4, 'Mejor Fotografía', 2025, 1, 'Premio a la mejor fotografía');
INSERT INTO premiacion (id_pelicula, categoria, edicion, posicion, descripcion) VALUES (5, 'Mejor Sonido', 2025, 1, 'Premio al mejor sonido');
