-- ===========================================
-- SCRIPT DE CREACIÓN DE TABLAS
-- Sistema de Gestión de Festival de Cine
-- ===========================================

-- Tabla: CIUDAD
CREATE TABLE ciudad (
    id_ciudad NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,
    region VARCHAR2(100) NOT NULL,
    pais VARCHAR2(50) DEFAULT 'Chile' NOT NULL,
    observaciones VARCHAR2(200) DEFAULT 'Sin observaciones' NOT NULL,
    CONSTRAINT pk_ciudad PRIMARY KEY (id_ciudad),
    CONSTRAINT uq_ciudad_nombre UNIQUE (nombre, region)
);

-- Tabla: SEDE
CREATE TABLE sede (
    id_sede NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,
    direccion VARCHAR2(150) NOT NULL,
    capacidad_maxima NUMBER DEFAULT 100 NOT NULL,
    tipo_sede VARCHAR2(50) DEFAULT 'Cine convencional' NOT NULL,
    id_ciudad NUMBER NOT NULL,
    estado VARCHAR2(20) DEFAULT 'Activa' NOT NULL,
    CONSTRAINT pk_sede PRIMARY KEY (id_sede),
    CONSTRAINT fk_sede_ciudad FOREIGN KEY (id_ciudad) REFERENCES ciudad(id_ciudad),
    CONSTRAINT uq_sede_nombre UNIQUE (nombre, id_ciudad),
    CONSTRAINT ck_capacidad_positiva CHECK (capacidad_maxima > 0),
    CONSTRAINT ck_estado_sede CHECK (estado IN ('Activa', 'Inactiva', 'Mantenimiento'))
);

-- Tabla: PELICULA
CREATE TABLE pelicula (
    id_pelicula NUMBER GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR2(100) NOT NULL,
    pais_origen VARCHAR2(50) NOT NULL,
    director VARCHAR2(100) NOT NULL,
    duracion_minutos NUMBER NOT NULL,
    genero VARCHAR2(50) DEFAULT 'Drama' NOT NULL,
    clasificacion VARCHAR2(10) DEFAULT 'TE' NOT NULL,
    sinopsis VARCHAR2(500) DEFAULT 'Sin sinopsis disponible' NOT NULL,
    CONSTRAINT pk_pelicula PRIMARY KEY (id_pelicula),
    CONSTRAINT uq_pelicula_titulo UNIQUE (titulo, director),
    CONSTRAINT ck_duracion_positiva CHECK (duracion_minutos > 0),
    CONSTRAINT ck_clasificacion_valida CHECK (clasificacion IN ('TE', '+7', '+14', '+18'))
);

-- Tabla: FUNCION
CREATE TABLE funcion (
    id_funcion NUMBER GENERATED BY DEFAULT AS IDENTITY,
    fecha DATE NOT NULL,
    hora VARCHAR2(10) NOT NULL,
    precio_entrada NUMBER DEFAULT 5000 NOT NULL,
    estado_funcion VARCHAR2(20) DEFAULT 'Programada' NOT NULL,
    observaciones VARCHAR2(200) DEFAULT 'Sin observaciones' NOT NULL,
    id_sede NUMBER NOT NULL,
    CONSTRAINT pk_funcion PRIMARY KEY (id_funcion),
    CONSTRAINT fk_funcion_sede FOREIGN KEY (id_sede) REFERENCES sede(id_sede),
    CONSTRAINT ck_precio_positivo CHECK (precio_entrada > 0),
    CONSTRAINT ck_estado_funcion CHECK (estado_funcion IN ('Programada', 'En curso', 'Finalizada', 'Cancelada'))
);

-- Tabla: PROYECCION
CREATE TABLE proyeccion (
    id_funcion NUMBER NOT NULL,
    id_pelicula NUMBER NOT NULL,
    orden_proyeccion NUMBER DEFAULT 1 NOT NULL,
    comentarios VARCHAR2(200) DEFAULT 'Sin comentarios' NOT NULL,
    CONSTRAINT pk_proyeccion PRIMARY KEY (id_funcion, id_pelicula),
    CONSTRAINT fk_proyeccion_funcion FOREIGN KEY (id_funcion) REFERENCES funcion(id_funcion),
    CONSTRAINT fk_proyeccion_pelicula FOREIGN KEY (id_pelicula) REFERENCES pelicula(id_pelicula),
    CONSTRAINT ck_orden_positivo CHECK (orden_proyeccion > 0)
);

-- Tabla: ASISTENTE
CREATE TABLE asistente (
    id_asistente NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,
    correo VARCHAR2(100) NOT NULL,
    telefono VARCHAR2(20) NOT NULL,
    edad NUMBER NOT NULL,
    ciudad_residencia VARCHAR2(100) DEFAULT 'No especificada' NOT NULL,
    tipo_asistente VARCHAR2(20) DEFAULT 'General' NOT NULL,
    CONSTRAINT pk_asistente PRIMARY KEY (id_asistente),
    CONSTRAINT uq_asistente_correo UNIQUE (correo),
    CONSTRAINT uq_asistente_telefono UNIQUE (telefono),
    CONSTRAINT ck_edad_valida CHECK (edad >= 0 AND edad <= 120),
    CONSTRAINT ck_tipo_asistente CHECK (tipo_asistente IN ('General', 'Estudiante', 'Profesional', 'Prensa'))
);

-- Tabla: ASISTENCIA
CREATE TABLE asistencia (
    id_funcion NUMBER NOT NULL,
    id_asistente NUMBER NOT NULL,
    entradas NUMBER DEFAULT 1 NOT NULL,
    fecha_compra DATE DEFAULT SYSDATE NOT NULL,
    metodo_pago VARCHAR2(20) DEFAULT 'Efectivo' NOT NULL,
    comentarios VARCHAR2(200) DEFAULT 'Sin comentarios' NOT NULL,
    CONSTRAINT pk_asistencia PRIMARY KEY (id_funcion, id_asistente),
    CONSTRAINT fk_asistencia_funcion FOREIGN KEY (id_funcion) REFERENCES funcion(id_funcion),
    CONSTRAINT fk_asistencia_asistente FOREIGN KEY (id_asistente) REFERENCES asistente(id_asistente),
    CONSTRAINT ck_entradas_positivas CHECK (entradas > 0),
    CONSTRAINT ck_metodo_pago CHECK (metodo_pago IN ('Efectivo', 'Tarjeta', 'Transferencia'))
);

-- Tabla: JURADO
CREATE TABLE jurado (
    id_jurado NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,
    correo VARCHAR2(100) NOT NULL,
    especialidad VARCHAR2(100) NOT NULL,
    pais_origen VARCHAR2(50) DEFAULT 'Chile' NOT NULL,
    experiencia_anos NUMBER DEFAULT 0 NOT NULL,
    tipo_jurado VARCHAR2(20) DEFAULT 'Invitado' NOT NULL,
    biografia VARCHAR2(500) DEFAULT 'Sin biografia disponible' NOT NULL,
    CONSTRAINT pk_jurado PRIMARY KEY (id_jurado),
    CONSTRAINT uq_jurado_correo UNIQUE (correo),
    CONSTRAINT ck_experiencia_valida CHECK (experiencia_anos >= 0),
    CONSTRAINT ck_tipo_jurado CHECK (tipo_jurado IN ('Invitado', 'Permanente', 'Honorario'))
);

-- Tabla: PARTICIPACION_JURADO
CREATE TABLE participacion_jurado (
    id_jurado NUMBER NOT NULL,
    id_funcion NUMBER NOT NULL,
    rol_participacion VARCHAR2(50) DEFAULT 'Evaluador' NOT NULL,
    comentarios VARCHAR2(200) DEFAULT 'Sin comentarios' NOT NULL,
    CONSTRAINT pk_participacion_jurado PRIMARY KEY (id_jurado, id_funcion),
    CONSTRAINT fk_part_jurado FOREIGN KEY (id_jurado) REFERENCES jurado(id_jurado),
    CONSTRAINT fk_part_funcion FOREIGN KEY (id_funcion) REFERENCES funcion(id_funcion),
    CONSTRAINT ck_rol_participacion CHECK (rol_participacion IN ('Evaluador', 'Moderador', 'Invitado especial'))
);

-- Tabla: EVALUACION
CREATE TABLE evaluacion (
    id_jurado NUMBER NOT NULL,
    id_pelicula NUMBER NOT NULL,
    puntuacion NUMBER NOT NULL,
    comentario VARCHAR2(500) DEFAULT 'Sin comentarios' NOT NULL,
    fecha_evaluacion DATE DEFAULT SYSDATE NOT NULL,
    categoria_evaluada VARCHAR2(50) DEFAULT 'General' NOT NULL,
    CONSTRAINT pk_evaluacion PRIMARY KEY (id_jurado, id_pelicula),
    CONSTRAINT fk_eval_jurado FOREIGN KEY (id_jurado) REFERENCES jurado(id_jurado),
    CONSTRAINT fk_eval_pelicula FOREIGN KEY (id_pelicula) REFERENCES pelicula(id_pelicula),
    CONSTRAINT ck_puntuacion_valida CHECK (puntuacion >= 1 AND puntuacion <= 10),
    CONSTRAINT ck_categoria_eval CHECK (categoria_evaluada IN ('General', 'Direccion', 'Actuacion', 'Guion', 'Fotografia', 'Sonido'))
);

-- Tabla: PREMIACION
CREATE TABLE premiacion (
    id_premio NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_pelicula NUMBER NOT NULL,
    categoria VARCHAR2(100) NOT NULL,
    edicion NUMBER NOT NULL,
    posicion NUMBER DEFAULT 1 NOT NULL,
    descripcion VARCHAR2(300) DEFAULT 'Sin descripcion' NOT NULL,
    fecha_premiacion DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_premiacion PRIMARY KEY (id_premio),
    CONSTRAINT fk_premio_pelicula FOREIGN KEY (id_pelicula) REFERENCES pelicula(id_pelicula),
    CONSTRAINT uq_premio_categoria_edicion UNIQUE (categoria, edicion, posicion),
    CONSTRAINT ck_edicion_valida CHECK (edicion > 0),
    CONSTRAINT ck_posicion_valida CHECK (posicion >= 1 AND posicion <= 3)
);

-- Tabla: USUARIO (para autenticación del sistema)
CREATE TABLE usuario (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR2(50) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    nombre_completo VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    rol VARCHAR2(20) DEFAULT 'usuario' NOT NULL,
    activo NUMBER(1) DEFAULT 1 NOT NULL,
    fecha_creacion DATE DEFAULT SYSDATE NOT NULL,
    ultimo_acceso DATE,
    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uq_username UNIQUE (username),
    CONSTRAINT uq_email UNIQUE (email),
    CONSTRAINT ck_rol_usuario CHECK (rol IN ('admin', 'usuario', 'invitado')),
    CONSTRAINT ck_activo CHECK (activo IN (0, 1))
);

COMMIT;
