-- ===========================================
-- TABLAS DE BITÁCORA (AUDITORÍA)
-- Registran cambios en las tablas principales
-- ===========================================

-- Bitácora para PELICULA
CREATE TABLE bitacora_pelicula (
    id_bitacora NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_pelicula NUMBER NOT NULL,
    operacion VARCHAR2(10) NOT NULL,
    titulo_anterior VARCHAR2(100),
    titulo_nuevo VARCHAR2(100),
    director_anterior VARCHAR2(100),
    director_nuevo VARCHAR2(100),
    duracion_anterior NUMBER,
    duracion_nueva NUMBER,
    usuario VARCHAR2(50),
    fecha_operacion DATE DEFAULT SYSDATE,
    CONSTRAINT pk_bitacora_pelicula PRIMARY KEY (id_bitacora),
    CONSTRAINT ck_operacion_pelicula CHECK (operacion IN ('INSERT', 'UPDATE', 'DELETE'))
);

-- Bitácora para FUNCION
CREATE TABLE bitacora_funcion (
    id_bitacora NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_funcion NUMBER NOT NULL,
    operacion VARCHAR2(10) NOT NULL,
    fecha_anterior DATE,
    fecha_nueva DATE,
    precio_anterior NUMBER,
    precio_nuevo NUMBER,
    estado_anterior VARCHAR2(20),
    estado_nuevo VARCHAR2(20),
    usuario VARCHAR2(50),
    fecha_operacion DATE DEFAULT SYSDATE,
    CONSTRAINT pk_bitacora_funcion PRIMARY KEY (id_bitacora),
    CONSTRAINT ck_operacion_funcion CHECK (operacion IN ('INSERT', 'UPDATE', 'DELETE'))
);

-- Bitácora para ASISTENCIA
CREATE TABLE bitacora_asistencia (
    id_bitacora NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_funcion NUMBER NOT NULL,
    id_asistente NUMBER NOT NULL,
    operacion VARCHAR2(10) NOT NULL,
    entradas_anterior NUMBER,
    entradas_nuevo NUMBER,
    metodo_pago_anterior VARCHAR2(20),
    metodo_pago_nuevo VARCHAR2(20),
    usuario VARCHAR2(50),
    fecha_operacion DATE DEFAULT SYSDATE,
    CONSTRAINT pk_bitacora_asistencia PRIMARY KEY (id_bitacora),
    CONSTRAINT ck_operacion_asistencia CHECK (operacion IN ('INSERT', 'UPDATE', 'DELETE'))
);

-- Bitácora para EVALUACION
CREATE TABLE bitacora_evaluacion (
    id_bitacora NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_jurado NUMBER NOT NULL,
    id_pelicula NUMBER NOT NULL,
    operacion VARCHAR2(10) NOT NULL,
    puntuacion_anterior NUMBER,
    puntuacion_nueva NUMBER,
    comentario_anterior VARCHAR2(500),
    comentario_nuevo VARCHAR2(500),
    usuario VARCHAR2(50),
    fecha_operacion DATE DEFAULT SYSDATE,
    CONSTRAINT pk_bitacora_evaluacion PRIMARY KEY (id_bitacora),
    CONSTRAINT ck_operacion_evaluacion CHECK (operacion IN ('INSERT', 'UPDATE', 'DELETE'))
);

-- Bitácora para USUARIO (login/acceso)
CREATE TABLE bitacora_usuario (
    id_bitacora NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario NUMBER NOT NULL,
    username VARCHAR2(50) NOT NULL,
    operacion VARCHAR2(20) NOT NULL,
    ip_address VARCHAR2(50),
    resultado VARCHAR2(20),
    mensaje VARCHAR2(200),
    fecha_operacion DATE DEFAULT SYSDATE,
    CONSTRAINT pk_bitacora_usuario PRIMARY KEY (id_bitacora),
    CONSTRAINT ck_operacion_usuario CHECK (operacion IN ('LOGIN', 'LOGOUT', 'FAILED_LOGIN', 'UPDATE', 'DELETE')),
    CONSTRAINT ck_resultado CHECK (resultado IN ('EXITOSO', 'FALLIDO', NULL))
);

COMMIT;
